"""Resource base — holds the transport and the page-building helper.

The sync twin is generated by unasync; edit only the async source.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, TypeVar

from midasbuy_sdk._async._transport import AsyncTransport
from midasbuy_sdk._pagination import DEFAULT_PAGE_SIZE, Page

T = TypeVar("T")


class AsyncResource:
    def __init__(self, transport: AsyncTransport) -> None:
        self._t = transport

    @staticmethod
    def _page(data: Any, model: Callable[[Any], T], *, limit: int, offset: int) -> Page[T]:
        items = [model(row) for row in (data or {}).get("items", [])]
        return Page(
            items=items,
            total=int((data or {}).get("total", len(items))),
            limit=limit,
            offset=offset,
            next_cursor=(data or {}).get("next_cursor"),
        )

    @staticmethod
    def _limit(limit: int | None) -> int:
        return DEFAULT_PAGE_SIZE if limit is None else limit
