# generated by datamodel-codegen:
#   filename:  openapi.public.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field, RootModel, SecretStr


class AccountEnv(StrEnum):
    """
    Which Midas environment an account targets (D-N1 / SDK §3.2).
    """

    online = "online"
    verify = "verify"


class AccountStatus(StrEnum):
    """
    Account vault lifecycle — also the worker claim state machine (D-15):
    CONNECTING is the claimable PENDING, RUNNING the in-flight claim, CONNECTED/
    FAILED the finalise terminals, EXPIRED the relogin loop's unrefreshable marker.

    REVOKED is the operator terminal — set only by an explicit back-office revoke,
    never by the worker. The worker only ever claims CONNECTING, so a REVOKED row
    is never claimed; account-selection (``first_connected``) filters CONNECTED,
    so a REVOKED row is never handed to redeem / buy-links either.
    """

    connecting = "connecting"
    running = "running"
    connected = "connected"
    failed = "failed"
    expired = "expired"
    revoked = "revoked"


class ActivateByDenominationRequest(BaseModel):
    """
    Activate using a stocked code of a denomination — no explicit code on input.

    The service picks a RANDOM available code of ``(game, denomination_value)``
    from the caller's inventory and drives a standalone activation with it; the
    customer never names a specific code (D-33).
    """

    account_id: Annotated[str, Field(max_length=26, min_length=1, title="Account Id")]
    denomination_value: Annotated[int, Field(gt=0, title="Denomination Value")]
    game: Annotated[str, Field(max_length=64, min_length=1, title="Game")]
    player_id: Annotated[str | None, Field(title="Player Id")] = None


class ActivateRequest(BaseModel):
    account_id: Annotated[str, Field(max_length=26, min_length=1, title="Account Id")]
    code: Annotated[SecretStr, Field(title="Code")]
    game: Annotated[str, Field(max_length=64, min_length=1, title="Game")]
    player_id: Annotated[str | None, Field(title="Player Id")] = None


class ActivationState(StrEnum):
    pending = "pending"
    running = "running"
    success = "success"
    failed = "failed"
    indeterminate = "indeterminate"


class AddCodeItem(BaseModel):
    code: Annotated[SecretStr, Field(title="Code")]
    currency: Annotated[str | None, Field(max_length=8, title="Currency")] = ""
    denomination_value: Annotated[int, Field(gt=0, title="Denomination Value")]
    game: Annotated[str, Field(max_length=64, min_length=1, title="Game")]


class AddCodesRequest(BaseModel):
    items: Annotated[list[AddCodeItem], Field(min_length=1, title="Items")]


class AddCodesResult(BaseModel):
    added: Annotated[int, Field(title="Added")]
    invalid: Annotated[int, Field(title="Invalid")]
    skipped_duplicates: Annotated[int, Field(title="Skipped Duplicates")]


class BatchActivateByDenominationRequest(BaseModel):
    """
    Activate up to ``quantity`` random stocked codes of a denomination in one call.

    Each unit is one activation and consumes one activation from the account-master
    quota. ``quantity`` is hard-capped at 1000 here and further bounded by the
    server's ``batch_max_size`` setting. When the quota is short, the global
    ``batch_strict_quota_check`` flag decides between a trimmed batch and an
    overspend (see the service).
    """

    account_id: Annotated[str, Field(max_length=26, min_length=1, title="Account Id")]
    denomination_value: Annotated[int, Field(gt=0, title="Denomination Value")]
    game: Annotated[str, Field(max_length=64, min_length=1, title="Game")]
    player_id: Annotated[str | None, Field(title="Player Id")] = None
    quantity: Annotated[int, Field(ge=1, le=1000, title="Quantity")]


class BatchActivationAccepted(BaseModel):
    """
    Batch outcome — how many were requested vs actually accepted, and their ids.

    ``accepted`` can be below ``requested`` when the batch was trimmed to the
    remaining quota (strict) or ran out of stocked codes.
    """

    accepted: Annotated[int, Field(title="Accepted")]
    activation_ids: Annotated[list[str], Field(title="Activation Ids")]
    requested: Annotated[int, Field(title="Requested")]
    status: ActivationState


class BatchItem(BaseModel):
    code: Annotated[SecretStr, Field(title="Code")]
    game: Annotated[str, Field(max_length=64, min_length=1, title="Game")]
    player_id: Annotated[str, Field(max_length=128, min_length=1, title="Player Id")]


class WebhookUrl(RootModel[AnyUrl]):
    root: Annotated[AnyUrl, Field(title="Webhook Url")]


class BatchRequest(BaseModel):
    account_id: Annotated[str, Field(max_length=26, min_length=1, title="Account Id")]
    items: Annotated[list[BatchItem], Field(min_length=1, title="Items")]
    webhook_url: Annotated[WebhookUrl | None, Field(title="Webhook Url")] = None


class BatchStatusRequest(BaseModel):
    activation_ids: Annotated[
        list[str], Field(max_length=100, min_length=1, title="Activation Ids")
    ]


class CatalogItem(BaseModel):
    currency: Annotated[str, Field(title="Currency")]
    game: Annotated[str, Field(title="Game")]
    item_id: Annotated[str, Field(title="Item Id")]
    price: Annotated[str, Field(title="Price")]
    title: Annotated[str, Field(title="Title")]


class Character(BaseModel):
    """
    The in-game role resolved for a looked-up player id.
    """

    game: Annotated[str, Field(title="Game")]
    is_ban: Annotated[bool | None, Field(title="Is Ban")] = False
    player_id: Annotated[str, Field(title="Player Id")]
    region: Annotated[str | None, Field(title="Region")] = None
    role_name: Annotated[str, Field(title="Role Name")]


class CharacterList(BaseModel):
    """
    Pageable list of characters for an account + game.
    """

    items: Annotated[list[Character], Field(title="Items")]


class CharacterRefreshRequest(BaseModel):
    account_id: Annotated[str, Field(max_length=26, min_length=1, title="Account Id")]


class CodeStatus(StrEnum):
    """
    A stocked redeem code's lifecycle.

    AVAILABLE → RESERVED (atomic reserve into a task) → USED (activation SUCCESS)
    or back to AVAILABLE (activation non-SUCCESS, released by the aggregator).
    INVALID marks a code rejected by shape validation on import.
    """

    available = "available"
    reserved = "reserved"
    used = "used"
    invalid = "invalid"


class CodeStock(BaseModel):
    available: Annotated[int, Field(title="Available")]
    currency: Annotated[str, Field(title="Currency")]
    denomination_value: Annotated[int, Field(title="Denomination Value")]
    game: Annotated[str, Field(title="Game")]
    total: Annotated[int, Field(title="Total")]


class Country(StrEnum):
    """
    ISO-3166-1 alpha-2 subset the gateway accepts as a region.
    """

    US = "US"
    BR = "BR"
    ID = "ID"
    TH = "TH"
    PH = "PH"
    VN = "VN"
    MY = "MY"
    SG = "SG"
    IN = "IN"
    TR = "TR"
    RU = "RU"
    MX = "MX"
    EG = "EG"
    SA = "SA"
    AE = "AE"
    PK = "PK"
    TW = "TW"
    HK = "HK"
    KR = "KR"
    JP = "JP"


class DataResponseAddCodesResult(BaseModel):
    data: AddCodesResult


class DataResponseBatchActivationAccepted(BaseModel):
    data: BatchActivationAccepted


class DataResponseCatalogItem(BaseModel):
    data: CatalogItem


class DataResponseCharacterList(BaseModel):
    data: CharacterList


class DataResponseCharacter(BaseModel):
    data: Character


class Game(BaseModel):
    item_id_prefix: Annotated[str, Field(title="Item Id Prefix")]
    slug: Annotated[str, Field(title="Slug")]
    title: Annotated[str, Field(title="Title")]


class InventoryItem(BaseModel):
    code_id: Annotated[str, Field(title="Code Id")]
    currency: Annotated[str, Field(title="Currency")]
    denomination_value: Annotated[int, Field(title="Denomination Value")]
    game: Annotated[str, Field(title="Game")]
    status: CodeStatus


class PackageRequest(BaseModel):
    account_id: Annotated[str, Field(max_length=26, min_length=1, title="Account Id")]
    amount: Annotated[int, Field(gt=0, title="Amount")]
    game: Annotated[str, Field(max_length=64, min_length=1, title="Game")]
    player_id: Annotated[str, Field(max_length=128, min_length=1, title="Player Id")]
    webhook_url: Annotated[WebhookUrl | None, Field(title="Webhook Url")] = None


class PageCatalogItem(BaseModel):
    items: Annotated[list[CatalogItem], Field(title="Items")]
    next_cursor: Annotated[str | None, Field(title="Next Cursor")] = None
    total: Annotated[int, Field(ge=0, title="Total")]


class PageCodeStock(BaseModel):
    items: Annotated[list[CodeStock], Field(title="Items")]
    next_cursor: Annotated[str | None, Field(title="Next Cursor")] = None
    total: Annotated[int, Field(ge=0, title="Total")]


class PageInventoryItem(BaseModel):
    items: Annotated[list[InventoryItem], Field(title="Items")]
    next_cursor: Annotated[str | None, Field(title="Next Cursor")] = None
    total: Annotated[int, Field(ge=0, title="Total")]


class RefreshAccepted(BaseModel):
    status: Annotated[str | None, Field(title="Status")] = "accepted"


class SubscriptionStatus(StrEnum):
    active = "active"
    expired = "expired"
    exhausted = "exhausted"
    revoked = "revoked"


class SubscriptionType(StrEnum):
    duration = "duration"
    quota = "quota"


class TaskItemResult(BaseModel):
    activation_id: Annotated[str, Field(title="Activation Id")]
    failure_code: Annotated[str | None, Field(title="Failure Code")] = None
    game: Annotated[str, Field(title="Game")]
    granted_item: Annotated[str | None, Field(title="Granted Item")] = None
    player_id: Annotated[str | None, Field(title="Player Id")] = None
    state: Annotated[str, Field(title="State")]


class TaskState(StrEnum):
    """
    Aggregate task lifecycle. PENDING/RUNNING are non-terminal; the three
    terminals are decided by the aggregator from the per-item outcomes (D-38):
    SUCCESS (all ok), PARTIAL (mixed), FAILED (none).
    """

    pending = "pending"
    running = "running"
    success = "success"
    partial = "partial"
    failed = "failed"


class TaskType(StrEnum):
    batch = "batch"
    package = "package"


class ValidationError(BaseModel):
    ctx: Annotated[dict[str, Any] | None, Field(title="Context")] = None
    input: Annotated[Any | None, Field(title="Input")] = None
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class Account(BaseModel):
    account_id: Annotated[str, Field(title="Account Id")]
    connected_at: Annotated[AwareDatetime | None, Field(title="Connected At")] = None
    label: Annotated[str | None, Field(title="Label")] = None
    midas_uid: Annotated[str | None, Field(title="Midas Uid")] = None
    status: AccountStatus


class AccountConnectAccepted(BaseModel):
    account_id: Annotated[str, Field(title="Account Id")]
    status: AccountStatus


class ActivationAccepted(BaseModel):
    activation_id: Annotated[str, Field(title="Activation Id")]
    status: ActivationState


class ActivationResult(BaseModel):
    activation_id: Annotated[str, Field(title="Activation Id")]
    failure_code: Annotated[str | None, Field(title="Failure Code")] = None
    finalised_at: Annotated[AwareDatetime | None, Field(title="Finalised At")] = None
    game: Annotated[str, Field(title="Game")]
    granted_item: Annotated[str | None, Field(title="Granted Item")] = None
    status: ActivationState


class BatchStatusResult(BaseModel):
    """
    The rows that resolved, plus the ids that did not.

    Unknown and cross-customer ids both land in ``missing`` — indistinguishable,
    so the endpoint cannot be used as an id oracle.
    """

    activations: Annotated[list[ActivationResult], Field(title="Activations")]
    missing: Annotated[list[str], Field(title="Missing")]


class ConnectAccountRequest(BaseModel):
    country: Country
    email: Annotated[EmailStr, Field(title="Email")]
    env: AccountEnv | None = "online"
    label: Annotated[str | None, Field(title="Label")] = None
    offer_id: Annotated[str | None, Field(title="Offer Id")] = "1450015065"
    password: Annotated[SecretStr, Field(title="Password")]


class DataResponseAccountConnectAccepted(BaseModel):
    data: AccountConnectAccepted


class DataResponseAccount(BaseModel):
    data: Account


class DataResponseActivationAccepted(BaseModel):
    data: ActivationAccepted


class DataResponseActivationResult(BaseModel):
    data: ActivationResult


class DataResponseBatchStatusResult(BaseModel):
    data: BatchStatusResult


class DataResponsePageCatalogItem(BaseModel):
    data: PageCatalogItem


class DataResponsePageCodeStock(BaseModel):
    data: PageCodeStock


class DataResponsePageInventoryItem(BaseModel):
    data: PageInventoryItem


class DataResponseRefreshAccepted(BaseModel):
    data: RefreshAccepted


class DataResponseListGame(BaseModel):
    data: Annotated[list[Game], Field(title="Data")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class PageAccount(BaseModel):
    items: Annotated[list[Account], Field(title="Items")]
    next_cursor: Annotated[str | None, Field(title="Next Cursor")] = None
    total: Annotated[int, Field(ge=0, title="Total")]


class PageActivationResult(BaseModel):
    items: Annotated[list[ActivationResult], Field(title="Items")]
    next_cursor: Annotated[str | None, Field(title="Next Cursor")] = None
    total: Annotated[int, Field(ge=0, title="Total")]


class SubscriptionStatusPublic(BaseModel):
    expires_at: Annotated[AwareDatetime | None, Field(title="Expires At")] = None
    rate_limit_per_min: Annotated[int, Field(title="Rate Limit Per Min")]
    remaining_quota: Annotated[int | None, Field(title="Remaining Quota")] = None
    status: SubscriptionStatus
    type: SubscriptionType


class TaskAccepted(BaseModel):
    state: TaskState
    task_id: Annotated[str, Field(title="Task Id")]


class TaskResult(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    done_count: Annotated[int, Field(title="Done Count")]
    finalised_at: Annotated[AwareDatetime | None, Field(title="Finalised At")] = None
    item_count: Annotated[int, Field(title="Item Count")]
    items: Annotated[list[TaskItemResult], Field(title="Items")]
    state: TaskState
    success_count: Annotated[int, Field(title="Success Count")]
    task_id: Annotated[str, Field(title="Task Id")]
    type: TaskType


class TaskSummary(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    done_count: Annotated[int, Field(title="Done Count")]
    finalised_at: Annotated[AwareDatetime | None, Field(title="Finalised At")] = None
    item_count: Annotated[int, Field(title="Item Count")]
    state: TaskState
    success_count: Annotated[int, Field(title="Success Count")]
    task_id: Annotated[str, Field(title="Task Id")]
    type: TaskType


class DataResponsePageAccount(BaseModel):
    data: PageAccount


class DataResponsePageActivationResult(BaseModel):
    data: PageActivationResult


class DataResponseSubscriptionStatusPublic(BaseModel):
    data: SubscriptionStatusPublic


class DataResponseTaskAccepted(BaseModel):
    data: TaskAccepted


class DataResponseTaskResult(BaseModel):
    data: TaskResult


class PageTaskSummary(BaseModel):
    items: Annotated[list[TaskSummary], Field(title="Items")]
    next_cursor: Annotated[str | None, Field(title="Next Cursor")] = None
    total: Annotated[int, Field(ge=0, title="Total")]


class DataResponsePageTaskSummary(BaseModel):
    data: PageTaskSummary
